export const actionPermissionDummyData = [
  {
    value: "APPROVE",
    name: "Approve",
    enumInt: 3,
  },
  {
    value: "FULL_RIGHTS",
    name: "Full Rights",
    enumInt: 2,
  },
  {
    value: "READ_ONLY",
    name: "Read Only",
    enumInt: 0,
  },
  {
    value: "READ_WRITE",
    name: "Read Write",
    enumInt: 1,
  },
];

export const systemProcessDummyData = [
  {
    value: "APPLICATION_REVIEW",
    name: "Application Review",
    enumInt: 0,
  },
  {
    value: "APPLICATIONS_MANAGEMENT",
    name: "Applications Management",
    enumInt: 2,
  },
  {
    value: "EVENTS_MANAGEMENT",
    name: "Events Management",
    enumInt: 7,
  },
  {
    value: "POSITIONS_MANAGEMENT",
    name: "Positions Management",
    enumInt: 5,
  },
  {
    value: "REVIEWER_ASSIGNMENT",
    name: "Reviewer Assignment",
    enumInt: 3,
  },
  {
    value: "REVIEWER_MANAGEMENT",
    name: "Reviewer Management",
    enumInt: 1,
  },
  {
    value: "SYSTEM_CONFIGURATION",
    name: "System Configuration",
    enumInt: 11,
  },
  {
    value: "SYSTEM_PERMISSIONS",
    name: "System Permissions",
    enumInt: 6,
  },
  {
    value: "TOT_CONFIGURATION",
    name: "Tot Configuration",
    enumInt: 10,
  },
  {
    value: "TOT_MANAGEMENT",
    name: "Tot Management",
    enumInt: 9,
  },
  {
    value: "USER_ACCOUNTS",
    name: "User Accounts",
    enumInt: 4,
  },
  {
    value: "USER_EVENTS",
    name: "User Events",
    enumInt: 8,
  },
];

export const systemModuleDummyData = [
  {
    value: "APPLICATIONS",
    name: "Applications",
    enumInt: 1,
  },
  {
    value: "EVENTS",
    name: "Events",
    enumInt: 5,
  },
  {
    value: "MONITORING_EVALUATION",
    name: "Monitoring Evaluation",
    enumInt: 4,
  },
  {
    value: "SYSTEM_CONFIG",
    name: "System Config",
    enumInt: 2,
  },
  {
    value: "TOT_MANAGEMENT",
    name: "Tot Management",
    enumInt: 3,
  },
  {
    value: "USER_MANAGEMENT",
    name: "User Management",
    enumInt: 0,
  },
];
export const permissionSetsDummyData = [
  {
    id: 1,
    module: "SYSTEM_CONFIG",
    systemProcess: "REVIEWER_ASSIGNMENT",
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 1,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: "FULL_RIGHTS",
        processId: null,
        userCount: 2,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: null,
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: null,
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 2,
    module: "SYSTEM_CONFIG",
    systemProcess: "REVIEWER_MANAGEMENT",
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 2,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: "FULL_RIGHTS",
        processId: null,
        userCount: 1,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: null,
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: null,
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 3,
    module: "APPLICATIONS",
    systemProcess: "APPLICATION_REVIEW",
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 3,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: "READ_ONLY",
        processId: null,
        userCount: 1,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: null,
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: null,
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 4,
    module: "TOT_MANAGEMENT",
    systemProcess: "TOT_CONFIGURATION",
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 4,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: "FULL_RIGHTS",
        processId: null,
        userCount: 3,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: null,
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: null,
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 5,
    module: "SYSTEM_CONFIG",
    systemProcess: "USER_ACCOUNTS",
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 5,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: "FULL_RIGHTS",
        processId: null,
        userCount: 2,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: null,
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: null,
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 6,
    module: "SYSTEM_CONFIG",
    systemProcess: "SYSTEM_PERMISSIONS",
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 6,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: "FULL_RIGHTS",
        processId: null,
        userCount: 1,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: null,
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: null,
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 7,
    module: "TOT_MANAGEMENT",
    systemProcess: "TOT_MANAGEMENT",
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 7,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: "FULL_RIGHTS",
        processId: null,
        userCount: 2,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: null,
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: null,
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 8,
    module: "SYSTEM_CONFIG",
    systemProcess: "POSITIONS_MANAGEMENT",
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 8,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: "FULL_RIGHTS",
        processId: null,
        userCount: 1,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: null,
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: null,
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
];

export const positionsDummyData = [
  {
    id: 1,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 1,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "General Manager",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 1,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_ASSIGNMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: "General Manager",
    abbrev: "GM",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 2,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [],
    userPermisssions: null,
    permissionIds: null,
    title: "Team Lead",
    abbrev: "TL",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 3,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 2,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Cleaner",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 3,
          module: "APPLICATIONS",
          systemProcess: "APPLICATION_REVIEW",
          actionPermissions: null,
          actionPermission: "READ_ONLY",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: "Cleaner",
    abbrev: "CL",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 4,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 6,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 2,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_MANAGEMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 5,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 1,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_ASSIGNMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 7,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 3,
          module: "APPLICATIONS",
          systemProcess: "APPLICATION_REVIEW",
          actionPermissions: null,
          actionPermission: "READ_ONLY",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 4,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 5,
          module: "SYSTEM_CONFIG",
          systemProcess: "USER_ACCOUNTS",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 3,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 4,
          module: "TOT_MANAGEMENT",
          systemProcess: "TOT_CONFIGURATION",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 3,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: "Trainer",
    abbrev: "TR",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 5,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 12,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 5,
          module: "SYSTEM_CONFIG",
          systemProcess: "USER_ACCOUNTS",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 8,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 1,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_ASSIGNMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 11,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 4,
          module: "TOT_MANAGEMENT",
          systemProcess: "TOT_CONFIGURATION",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 3,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 13,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 6,
          module: "SYSTEM_CONFIG",
          systemProcess: "SYSTEM_PERMISSIONS",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 9,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 2,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_MANAGEMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 10,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 3,
          module: "APPLICATIONS",
          systemProcess: "APPLICATION_REVIEW",
          actionPermissions: null,
          actionPermission: "READ_ONLY",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 14,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 7,
          module: "TOT_MANAGEMENT",
          systemProcess: "TOT_MANAGEMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 15,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 8,
          module: "SYSTEM_CONFIG",
          systemProcess: "POSITIONS_MANAGEMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: "SA",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
];

export const districtDummyData = [
  {
    districtname: null,
    districtcode: null,
    name: "Mukono",
    countryid: null,
    id: 1,
    code: "MUK",
    countryId: 1,
    districtId: null,
    countyId: null,
    subCountyId: null,
    parishId: null,
    parentName: null,
    parentId: null,
    countryName: "Uganda",
  },
];

export const countriesDummyData = {
  countries: [
    {
      countryname: null,
      countrycode: null,
      id: 1,
      natinality: "Ugandan",
      dailCode: "+256",
      name: "Uganda",
      code: "256",
    },
    {
      countryname: null,
      countrycode: null,
      id: 2,
      natinality: "Kenyan",
      dailCode: "+254",
      name: "Kenya",
      code: "254",
    },
  ],
  districts: [],
};

export const usersDummyData = [
  {
    id: 1,
    firstName: null,
    otherName: null,
    surname: "senyondo",
    dob: "1996-07-28T00:00:00.000+03:00",
    phoneNumber: "+256772077466",
    field: null,
    email: "admin@tibic.go.ug",
    status: null,
    location: null,
    ninNumber: "CM122345566666",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "STAFF",
    name: "senyondo",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 2,
    firstName: "",
    otherName: "",
    surname: "Daniel",
    dob: "1986-04-14T00:00:00.000+03:00",
    phoneNumber: "+256772898298",
    field: null,
    email: "dndannang@gmail.com",
    status: null,
    location: null,
    ninNumber: "CM86078103LQ0H",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "STAFF",
    name: "Daniel",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 4,
    firstName: null,
    otherName: null,
    surname: "",
    dob: null,
    phoneNumber: "",
    field: null,
    email: "",
    status: null,
    location: null,
    ninNumber: "",
    dateSubmitted: null,
    dateUpdated: null,
    gender: null,
    password: null,
    fullname: null,
    userType: "GUEST",
    name: "",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 5,
    firstName: "Kasasira",
    otherName: null,
    surname: "Joshua",
    dob: "1996-06-03T00:00:00.000+03:00",
    phoneNumber: "+256703503331",
    field: null,
    email: "joshkasas.14@gmail.com",
    status: null,
    location: null,
    ninNumber: "FVSBDJEIEBE782",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "STAFF",
    name: "Kasasira Joshua",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 7,
    firstName: null,
    otherName: null,
    surname: "Samantha",
    dob: "2020-01-01T00:00:00.000+03:00",
    phoneNumber: "+256703567777",
    field: null,
    email: "joshkasasira@yahoo.com",
    status: null,
    location: null,
    ninNumber: "NDSMDBHDFYW820",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "STAFF",
    name: "Samantha",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 8,
    firstName: null,
    otherName: null,
    surname: "Testing",
    dob: null,
    phoneNumber: "+256702943528",
    field: null,
    email: "jkasasira@ucu.ac.ug",
    status: null,
    location: null,
    ninNumber: "AKSBHIWDGV3843",
    dateSubmitted: null,
    dateUpdated: null,
    gender: null,
    password: null,
    fullname: null,
    userType: "STAFF",
    name: "Testing",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 9,
    firstName: null,
    otherName: null,
    surname: "tIBIC",
    dob: null,
    phoneNumber: "+256902825142",
    field: null,
    email: "joshkasas14@outlook.com",
    status: null,
    location: null,
    ninNumber: "KJSDVIJERBOIER",
    dateSubmitted: null,
    dateUpdated: null,
    gender: null,
    password: null,
    fullname: null,
    userType: "STAFF",
    name: "tIBIC",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 56,
    firstName: "Testrer",
    otherName: null,
    surname: "ALaph",
    dob: "2020-01-01T00:00:00.000+03:00",
    phoneNumber: "+256791234563",
    field: null,
    email: "masukawill@gmail.com",
    status: null,
    location: null,
    ninNumber: "WWFCJBVUE45632",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "STAFF",
    name: "Testrer ALaph",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 57,
    firstName: null,
    otherName: null,
    surname: "Moses",
    dob: "1985-10-05T00:00:00.000+03:00",
    phoneNumber: "+256785341161",
    field: null,
    email: "agaba.nice@gmail.com",
    status: null,
    location: null,
    ninNumber: "CM850651095XNL",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "STAFF",
    name: "Moses",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 58,
    firstName: "Kasasira",
    otherName: "",
    surname: "Joshua",
    dob: "2020-01-01T00:00:00.000+03:00",
    phoneNumber: "+256735678022",
    field: null,
    email: "arrowphoto6694061joshua@gmail.com",
    status: null,
    location: null,
    ninNumber: "ASBNMFKKDUW253",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "STAFF",
    name: "Kasasira Joshua",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 59,
    firstName: null,
    otherName: null,
    surname: "Okia",
    dob: null,
    phoneNumber: "+256773405000",
    field: null,
    email: "okiaisaack@gmail.com",
    status: null,
    location: null,
    ninNumber: "CM81035106F38D",
    dateSubmitted: null,
    dateUpdated: null,
    gender: null,
    password: null,
    fullname: null,
    userType: "GUEST",
    name: "Okia",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 60,
    firstName: "TIBIC",
    otherName: null,
    surname: "User",
    dob: "2004-01-01T00:00:00.000+03:00",
    phoneNumber: "(+256) 703 503 333",
    field: null,
    email: "trainee@tibic.go.ug",
    status: null,
    location: null,
    ninNumber: null,
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "GUEST",
    name: "TIBIC User",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: 4,
    staffId: 1,
    positionString: "Trainer",
    country: 1,
    district: 1,
  },
  {
    id: 61,
    firstName: "tibic",
    otherName: "",
    surname: "trainee",
    dob: "2005-07-02T00:00:00.000+03:00",
    phoneNumber: "(+256) 703 503 332",
    field: null,
    email: "teamleader@tibic.go.ug",
    status: null,
    location: null,
    ninNumber: "UDS NFMFDKDNME",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "GUEST",
    name: "tibic trainee",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: 2,
    staffId: 2,
    positionString: "Team Lead",
    country: 1,
    district: null,
  },
  {
    id: 66,
    firstName: "Ampaire",
    otherName: null,
    surname: "Evarest",
    dob: null,
    phoneNumber: "+256781716775",
    field: null,
    email: "ampaireevarest6@gmail.com",
    status: null,
    location: null,
    ninNumber: "CM12234556666877",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Ampaire Evarest",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 67,
    firstName: "Jordan Micheal",
    otherName: null,
    surname: "SENYONDO",
    dob: null,
    phoneNumber: "+256997654333",
    field: null,
    email: "jsenyondo@ucu.ac.ug",
    status: null,
    location: null,
    ninNumber: "UGANDASENYONDO",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Jordan Micheal SENYONDO",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 68,
    firstName: "Daniel",
    otherName: null,
    surname: "Nanghaka",
    dob: null,
    phoneNumber: "+256701355594",
    field: null,
    email: "daniel@nanghaka.com",
    status: null,
    location: null,
    ninNumber: "UGANDANanghaka",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Daniel Nanghaka",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 69,
    firstName: "Hakim",
    otherName: null,
    surname: "Zziwa Senyange",
    dob: null,
    phoneNumber: "+256703104008",
    field: null,
    email: "zhakim010@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAZziwa Senyange",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Hakim Zziwa Senyange",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 70,
    firstName: "BASOOMA",
    otherName: null,
    surname: "ISA",
    dob: null,
    phoneNumber: "+256784990353",
    field: null,
    email: "basoomaisa@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAISA",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "BASOOMA ISA",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 71,
    firstName: "Mugisha",
    otherName: null,
    surname: "Benjamin",
    dob: null,
    phoneNumber: "+256774781220",
    field: null,
    email: "bmugisha007@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDABenjamin",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Mugisha Benjamin",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 73,
    firstName: "NAKAYIMA",
    otherName: "",
    surname: "SUZAN",
    dob: "1994-01-28T00:00:00.000+03:00",
    phoneNumber: "+256788258446",
    field: null,
    email: "suzannakayima@gmail.com",
    status: null,
    location: null,
    ninNumber: "CF94013103MLGC",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "NAKAYIMA SUZAN",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: 1,
    district: null,
  },
  {
    id: 74,
    firstName: "MANZI",
    otherName: "",
    surname: "GERALD",
    dob: "1992-03-22T19:00:00.000+03:00",
    phoneNumber: "+256705190952",
    field: null,
    email: "manzi.gerald@yahoo.com",
    status: null,
    location: null,
    ninNumber: "MANZIGERALD CM9200910370JF",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "MANZI GERALD",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: 1,
    district: null,
  },
  {
    id: 75,
    firstName: "Kobusinge",
    otherName: null,
    surname: "Janet",
    dob: null,
    phoneNumber: "+256770841192",
    field: null,
    email: "kobusingejanet052@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAJanet",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Kobusinge Janet",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 77,
    firstName: "Isabirye",
    otherName: "watongola",
    surname: "Muzamiru",
    dob: null,
    phoneNumber: "+256758606508",
    field: null,
    email: "isabiryemuzamiru9@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAMuzamiru",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Isabirye Muzamiru watongola",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: 1,
    district: 1,
  },
  {
    id: 83,
    firstName: "Oboi",
    otherName: null,
    surname: "Augusten",
    dob: null,
    phoneNumber: "+256763562430",
    field: null,
    email: "augustineoboi@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAAugusten",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Oboi Augusten",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 86,
    firstName: "Alvin",
    otherName: null,
    surname: "Asingya",
    dob: null,
    phoneNumber: "+256772882664",
    field: null,
    email: "aasingya@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAAsingya",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Alvin Asingya",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 90,
    firstName: "Robert",
    otherName: null,
    surname: "Mulinzi Don",
    dob: null,
    phoneNumber: "+256772339374",
    field: null,
    email: "donmartin.jnd@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAMulinzi Don",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Robert Mulinzi Don",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 93,
    firstName: "Abura ",
    otherName: null,
    surname: "Morris ",
    dob: null,
    phoneNumber: "+256783828362",
    field: null,
    email: "aburamorris97@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAMorris ",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Abura Morris",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 99,
    firstName: "Alex",
    otherName: null,
    surname: "Mpango",
    dob: null,
    phoneNumber: "+256781316588",
    field: null,
    email: "mpangoalex7@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAMpango",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Alex Mpango",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 104,
    firstName: "Kasule",
    otherName: null,
    surname: "Daniel",
    dob: "2023-10-16T10:16:28.000+03:00",
    phoneNumber: "+256783660719",
    field: null,
    email: "kasuledaniel01@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDADaniel",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Kasule Daniel",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 110,
    firstName: "BONIFACE ",
    otherName: null,
    surname: "KASAJA ",
    dob: null,
    phoneNumber: "+256774601021",
    field: null,
    email: "bonifacekg@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAKASAJA ",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "BONIFACE KASAJA",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 112,
    firstName: "Baruga",
    otherName: null,
    surname: "Brian",
    dob: null,
    phoneNumber: "+256757519327",
    field: null,
    email: "ryansbri@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDABrian",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Baruga Brian",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 115,
    firstName: "DANIEL CONCORD",
    otherName: "",
    surname: "ACAR",
    dob: "1994-10-02T19:00:00.000+03:00",
    phoneNumber: "+256785265448",
    field: null,
    email: "acardaniel4@gmail.com",
    status: null,
    location: null,
    ninNumber: "CM94074100WFYF",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "DANIEL CONCORD ACAR",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: 1,
    district: null,
  },
  {
    id: 121,
    firstName: "Ronald ",
    otherName: null,
    surname: "Katwesige ",
    dob: null,
    phoneNumber: "+256778071719",
    field: null,
    email: "ronaldkatwesige350@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAKatwesige ",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Ronald Katwesige",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 123,
    firstName: "ARNOLD BRIAN",
    otherName: null,
    surname: "OULE",
    dob: null,
    phoneNumber: "+256785610957",
    field: null,
    email: "arnoldoule@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAOULE",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "ARNOLD BRIAN OULE",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 129,
    firstName: "Daniel",
    otherName: "",
    surname: "Tibagendeka",
    dob: "1990-02-22T00:00:00.000+03:00",
    phoneNumber: "+256754796426",
    field: null,
    email: "dtibagendeka@gmail.com",
    status: null,
    location: null,
    ninNumber: "CM90007106ACXH",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Daniel Tibagendeka",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: 1,
    district: 1,
  },
  {
    id: 131,
    firstName: "Pius",
    otherName: null,
    surname: "Nyanzi",
    dob: null,
    phoneNumber: "+256704350277",
    field: null,
    email: "piusnyanzi@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDANyanzi",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Pius Nyanzi",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 134,
    firstName: "JUMANYWAL",
    otherName: "",
    surname: "HOWARD",
    dob: "1989-01-26T03:00:00.000+03:00",
    phoneNumber: "+256783336089",
    field: null,
    email: "jumanywalhoward@gmail.com",
    status: null,
    location: null,
    ninNumber: "CM89033100V2XF",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "MALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "JUMANYWAL HOWARD",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: 1,
    district: null,
  },
  {
    id: 138,
    firstName: "Achire ",
    otherName: null,
    surname: "Michael West ",
    dob: null,
    phoneNumber: "+256774372919",
    field: null,
    email: "achire20082000@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAMichael West ",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Achire Michael West",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 144,
    firstName: "MUGANYIZI",
    otherName: null,
    surname: "JOSHUA",
    dob: null,
    phoneNumber: "+256773571644",
    field: null,
    email: "joshuamuganyizi28@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAJOSHUA",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "MUGANYIZI JOSHUA",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 150,
    firstName: "Daniel",
    otherName: null,
    surname: "Wangira",
    dob: null,
    phoneNumber: "+256701909565",
    field: null,
    email: "dan.wangira@gmail.com",
    status: null,
    location: null,
    ninNumber: "UGANDAWangira",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "TRAINEE",
    name: "Daniel Wangira",
    userStatus: "ACTIVE",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
  {
    id: 153,
    firstName: "ISABIRYE",
    otherName: null,
    surname: "MUZAMIRU",
    dob: null,
    phoneNumber: "+256705766807",
    field: null,
    email: "isabiryemuzamiru9@gmail.com.ug",
    status: null,
    location: null,
    ninNumber: "UGANDAMUZAMIRU",
    dateSubmitted: null,
    dateUpdated: null,
    gender: "FEMALE",
    password: null,
    fullname: null,
    userType: "GUEST",
    name: "ISABIRYE MUZAMIRU",
    userStatus: "SUSPENDED",
    signatureRequests: null,
    userDetails: null,
    permissionsIds: null,
    positionId: null,
    staffId: null,
    positionString: "NONE",
    country: null,
    district: null,
  },
];

export const permissionsDummyData = [
  {
    id: 1,
    module: "SYSTEM_CONFIG",
    systemProcess: "REVIEWER_ASSIGNMENT",
    actionPermissions: null,
    actionPermission: "FULL_RIGHTS",
    processId: null,
    userCount: 2,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 2,
    module: "SYSTEM_CONFIG",
    systemProcess: "REVIEWER_MANAGEMENT",
    actionPermissions: null,
    actionPermission: "FULL_RIGHTS",
    processId: null,
    userCount: 1,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 3,
    module: "APPLICATIONS",
    systemProcess: "APPLICATION_REVIEW",
    actionPermissions: null,
    actionPermission: "READ_ONLY",
    processId: null,
    userCount: 1,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 4,
    module: "TOT_MANAGEMENT",
    systemProcess: "TOT_CONFIGURATION",
    actionPermissions: null,
    actionPermission: "FULL_RIGHTS",
    processId: null,
    userCount: 3,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 5,
    module: "SYSTEM_CONFIG",
    systemProcess: "USER_ACCOUNTS",
    actionPermissions: null,
    actionPermission: "FULL_RIGHTS",
    processId: null,
    userCount: 2,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 6,
    module: "SYSTEM_CONFIG",
    systemProcess: "SYSTEM_PERMISSIONS",
    actionPermissions: null,
    actionPermission: "FULL_RIGHTS",
    processId: null,
    userCount: 1,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 7,
    module: "TOT_MANAGEMENT",
    systemProcess: "TOT_MANAGEMENT",
    actionPermissions: null,
    actionPermission: "FULL_RIGHTS",
    processId: null,
    userCount: 2,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 8,
    module: "SYSTEM_CONFIG",
    systemProcess: "POSITIONS_MANAGEMENT",
    actionPermissions: null,
    actionPermission: "FULL_RIGHTS",
    processId: null,
    userCount: 1,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: null,
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
];
export const positionStatusDummyData = [
  {
    value: "ACTIVE",
    name: "Active",
    enumInt: 0,
  },
  {
    value: "INACTIVE",
    name: "Inactive",
    enumInt: 1,
  },
];
export const positionDummyData = [
  {
    id: 1,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 1,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "General Manager",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 1,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_ASSIGNMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: "General Manager",
    abbrev: "GM",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 2,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [],
    userPermisssions: null,
    permissionIds: null,
    title: "Team Lead",
    abbrev: "TL",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 3,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 2,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Cleaner",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 3,
          module: "APPLICATIONS",
          systemProcess: "APPLICATION_REVIEW",
          actionPermissions: null,
          actionPermission: "READ_ONLY",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: "Cleaner",
    abbrev: "CL",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 4,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 4,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 5,
          module: "SYSTEM_CONFIG",
          systemProcess: "USER_ACCOUNTS",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 5,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 1,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_ASSIGNMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 6,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 2,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_MANAGEMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 3,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 4,
          module: "TOT_MANAGEMENT",
          systemProcess: "TOT_CONFIGURATION",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 3,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 7,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "Trainer",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 3,
          module: "APPLICATIONS",
          systemProcess: "APPLICATION_REVIEW",
          actionPermissions: null,
          actionPermission: "READ_ONLY",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: "Trainer",
    abbrev: "TR",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
  {
    id: 5,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: [
      {
        id: 11,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 4,
          module: "TOT_MANAGEMENT",
          systemProcess: "TOT_CONFIGURATION",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 3,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 8,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 1,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_ASSIGNMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 14,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 7,
          module: "TOT_MANAGEMENT",
          systemProcess: "TOT_MANAGEMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 10,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 3,
          module: "APPLICATIONS",
          systemProcess: "APPLICATION_REVIEW",
          actionPermissions: null,
          actionPermission: "READ_ONLY",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 12,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 5,
          module: "SYSTEM_CONFIG",
          systemProcess: "USER_ACCOUNTS",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 2,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 13,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 6,
          module: "SYSTEM_CONFIG",
          systemProcess: "SYSTEM_PERMISSIONS",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 9,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 2,
          module: "SYSTEM_CONFIG",
          systemProcess: "REVIEWER_MANAGEMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
      {
        id: 15,
        module: null,
        systemProcess: null,
        actionPermissions: null,
        actionPermission: null,
        processId: null,
        userCount: 0,
        permissions: null,
        userPermisssions: null,
        permissionIds: null,
        title: "System Admin",
        abbrev: null,
        positionStatus: null,
        details: null,
        permissionsIds: null,
        positionId: null,
        permissionId: null,
        permissionsDetails: {
          id: 8,
          module: "SYSTEM_CONFIG",
          systemProcess: "POSITIONS_MANAGEMENT",
          actionPermissions: null,
          actionPermission: "FULL_RIGHTS",
          processId: null,
          userCount: 1,
          permissions: null,
          userPermisssions: null,
          permissionIds: null,
          title: null,
          abbrev: null,
          positionStatus: null,
          details: null,
          permissionsIds: null,
          positionId: null,
          permissionId: null,
          permissionsDetails: null,
          userId: null,
        },
        userId: null,
      },
    ],
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: "SA",
    positionStatus: "ACTIVE",
    details: "",
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: null,
    userId: null,
  },
];

export const positionPermissionsDummyData = [
  {
    id: 1,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "General Manager",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 1,
      module: "SYSTEM_CONFIG",
      systemProcess: "REVIEWER_ASSIGNMENT",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 2,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 2,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "Cleaner",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 3,
      module: "APPLICATIONS",
      systemProcess: "APPLICATION_REVIEW",
      actionPermissions: null,
      actionPermission: "READ_ONLY",
      processId: null,
      userCount: 1,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 3,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "Trainer",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 4,
      module: "TOT_MANAGEMENT",
      systemProcess: "TOT_CONFIGURATION",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 3,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 4,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "Trainer",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 5,
      module: "SYSTEM_CONFIG",
      systemProcess: "USER_ACCOUNTS",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 2,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 5,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "Trainer",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 1,
      module: "SYSTEM_CONFIG",
      systemProcess: "REVIEWER_ASSIGNMENT",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 2,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 6,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "Trainer",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 2,
      module: "SYSTEM_CONFIG",
      systemProcess: "REVIEWER_MANAGEMENT",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 1,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 7,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "Trainer",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 3,
      module: "APPLICATIONS",
      systemProcess: "APPLICATION_REVIEW",
      actionPermissions: null,
      actionPermission: "READ_ONLY",
      processId: null,
      userCount: 1,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 8,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 1,
      module: "SYSTEM_CONFIG",
      systemProcess: "REVIEWER_ASSIGNMENT",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 2,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 9,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 2,
      module: "SYSTEM_CONFIG",
      systemProcess: "REVIEWER_MANAGEMENT",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 1,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 10,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 3,
      module: "APPLICATIONS",
      systemProcess: "APPLICATION_REVIEW",
      actionPermissions: null,
      actionPermission: "READ_ONLY",
      processId: null,
      userCount: 1,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 11,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 4,
      module: "TOT_MANAGEMENT",
      systemProcess: "TOT_CONFIGURATION",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 3,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 12,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 5,
      module: "SYSTEM_CONFIG",
      systemProcess: "USER_ACCOUNTS",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 2,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 13,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 6,
      module: "SYSTEM_CONFIG",
      systemProcess: "SYSTEM_PERMISSIONS",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 1,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 14,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 7,
      module: "TOT_MANAGEMENT",
      systemProcess: "TOT_MANAGEMENT",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 2,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
  {
    id: 15,
    module: null,
    systemProcess: null,
    actionPermissions: null,
    actionPermission: null,
    processId: null,
    userCount: 0,
    permissions: null,
    userPermisssions: null,
    permissionIds: null,
    title: "System Admin",
    abbrev: null,
    positionStatus: null,
    details: null,
    permissionsIds: null,
    positionId: null,
    permissionId: null,
    permissionsDetails: {
      id: 8,
      module: "SYSTEM_CONFIG",
      systemProcess: "POSITIONS_MANAGEMENT",
      actionPermissions: null,
      actionPermission: "FULL_RIGHTS",
      processId: null,
      userCount: 1,
      permissions: null,
      userPermisssions: null,
      permissionIds: null,
      title: null,
      abbrev: null,
      positionStatus: null,
      details: null,
      permissionsIds: null,
      positionId: null,
      permissionId: null,
      permissionsDetails: null,
      userId: null,
    },
    userId: null,
  },
];
